# The order is "oldest we support" → "current stable" → "latest preview"
versions:
  - "3.6.22"   # LTS floor you support
  - "4.2.10"    # Current stable / Extensions baseline
  #- "stable" # Optional / bleeding edge (can be opt-in)
  
# Optional paths to Blender executables for each version
# Versions must match EXACTLY.
paths:
  "3.6.22": "/Applications/Blender 3.6.22 LTS.app/Contents/MacOS/Blender"
  #"4.2.10": "/Applications/Blender 4.2.10.app/Contents/MacOS/Blender"