name: CI

on: [push, pull_request]

jobs:
  combined:
    strategy:
      fail-fast: false
      matrix:
        blender_ver: [ "3.6.22", "4.2.0" ]  # minimal required; extend as needed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install pytest pyyaml pytest-blender blender-downloader
      - name: Fetch Blender
        run: |
          python "$GITHUB_WORKSPACE/scripts/fetch_blenders.py"
          echo "BLENDER_EXE=$(ls .blcache/${{ matrix.blender_ver }}/**/blender 2>/dev/null | head -n1)" >> $GITHUB_ENV
      - name: Run integration tests
        env:
          BLENDER_EXE: "" # will be overwritten
          PYTHONPATH: ${{ github.workspace }}/src
          BLENDER_INTEGRATION_EXE: ${{ env.BLENDER_EXE }}
        run: |
          python "$GITHUB_WORKSPACE/run_tests.py"
