name: CI

on: [pull_request]

jobs:
  combined:
    strategy:
      fail-fast: false
      matrix:
        blender_ver: [ "3.6.22", "4.2.0" ]  # minimal required; extend as needed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install the runtime libraries Blender needs
      - name: Install Blender runtime deps (X11 + Mesa)
        if: ${{ env.ACT == 'true' }} # Only required for act
        run: |
          apt-get update -y
          # minimal set; pulls in libXxf86vm, libXrender, etc. via dependencies
          DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
            xorg \
            libgl1-mesa-glx \
            libegl1-mesa
          apt-get clean
          rm -rf /var/lib/apt/lists/*
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install pytest pyyaml pytest-blender blender-downloader
      - name: Fetch Blender
        run: |
          python "$GITHUB_WORKSPACE/scripts/fetch_blenders.py"
          echo "BLENDER_EXE=$(ls .blcache/${{ matrix.blender_ver }}/**/blender 2>/dev/null | head -n1)" >> $GITHUB_ENV
      - name: Run integration tests
        env:
          BLENDER_EXE: "" # will be overwritten
          PYTHONPATH: ${{ github.workspace }}/src
          BLENDER_INTEGRATION_EXE: ${{ env.BLENDER_EXE }}
        run: |
          python "$GITHUB_WORKSPACE/run_tests.py"
